create table bhuser (
  bhuserid number generated by default on null as identity,
  username varchar(50) not null,
  userpassword varchar(50) not null,
  motto varchar(100) default null,
  useremail varchar(100) not null,
  joindate date default sysdate
);

create table bhpost (
  postid number generated by default on null as identity, 
  postdate date default sysdate,
  posttext varchar(141) default null,
  bhuserid number default null
);

