create table bhuser (
  bhuserid number generated by default on null as identity,
  username varchar(50) not null,
  userpassword varchar(50) not null,
  motto varchar(100) default null,
  useremail varchar(100) not null,
  joindate date default sysdate
);

create table bhpost (
  postid number generated by default on null as identity, 
  postdate date default sysdate,
  posttext varchar(141) default null,
  bhuserid number default null
);

alter table bhuser add constraint bhuser_pk primary key (bhuserid);
alter table bhpost add constraint bhpost_pk primary key (postid);
alter table bhpost add constraint bhpost_fk foreign key (bhuserid) references  bhuser (bhuserid);
